// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/[id].tsx';
import * as $1 from './routes/_404.tsx';
import * as $2 from './routes/_500.tsx';
import * as $3 from './routes/_503.tsx';
import * as $4 from './routes/_app.tsx';
import * as $5 from './routes/api/publish.ts';
import * as $6 from './routes/index.tsx';
import * as $$0 from './islands/Manage.tsx';

const manifest = {
  routes: {
    './routes/[id].tsx': $0,
    './routes/_404.tsx': $1,
    './routes/_500.tsx': $2,
    './routes/_503.tsx': $3,
    './routes/_app.tsx': $4,
    './routes/api/publish.ts': $5,
    './routes/index.tsx': $6,
  },
  islands: {
    './islands/Manage.tsx': $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
